from __future__ import annotations

from dataclasses import dataclass, field

import numpy as np

from retention_rl.memory import (
    EpisodeRecord,
    ValuableEpisodicMemory,
)
from retention_rl.retention.stored_action_log_prob import (
    trajectory_nll,
)


@dataclass
class EpisodeTracker:
    """
    Collect one complete environment episode.

    State convention:
        states  = [s_0, s_1, ..., s_T]
        actions = [a_0, a_1, ..., a_{T-1}]
        rewards = [r_0, r_1, ..., r_{T-1}]

    Therefore:
        len(states) = T + 1
        len(actions) = T
        len(rewards) = T

    An episode is eligible for Valuable Episodic Memory only when
    every action was generated by the policy.

    initial_env_state stores the physical simulator state at s_0 so
    the episode can later be revisited by the current policy.
    """

    episode_id: int

    states: list = field(
        default_factory=list
    )

    actions: list = field(
        default_factory=list
    )

    rewards: list = field(
        default_factory=list
    )

    policy_generated: bool = True

    initial_env_state: object | None = None

    def start(
        self,
        initial_state,
        initial_env_state=None,
    ):
        """
        Start or reset episode tracking.

        initial_state:
            Observation s_0.

        initial_env_state:
            Optional exact simulator state corresponding to s_0.
        """

        self.states = [
            np.asarray(
                initial_state,
                dtype=np.float32,
            ).copy()
        ]

        self.actions = []
        self.rewards = []

        self.policy_generated = True

        self.initial_env_state = initial_env_state

    def add_transition(
        self,
        action,
        reward,
        next_state,
        action_from_policy: bool,
    ):
        """
        Add one transition:

            s_t, a_t, r_t, s_{t+1}

        The current s_t is already the final item in self.states.
        """

        if len(self.states) == 0:
            raise RuntimeError(
                "EpisodeTracker.start() must be called "
                "before add_transition()."
            )

        self.actions.append(
            np.asarray(
                action,
                dtype=np.float32,
            ).copy()
        )

        self.rewards.append(
            float(reward)
        )

        self.states.append(
            np.asarray(
                next_state,
                dtype=np.float32,
            ).copy()
        )

        if not action_from_policy:
            self.policy_generated = False

    @property
    def length(self) -> int:
        return len(
            self.actions
        )

    @property
    def episode_return(self) -> float:
        return float(
            np.sum(
                self.rewards,
                dtype=np.float64,
            )
        )

    def finalize(
        self,
        actor,
        insert_step: int,
    ) -> EpisodeRecord | None:
        """
        Convert the tracked episode into an EpisodeRecord.

        Returns None when the episode contains at least one
        non-policy action, such as an action generated during
        SAC random warm-up.
        """

        if self.length == 0:
            raise RuntimeError(
                "Cannot finalize an empty episode."
            )

        if not self.policy_generated:
            return None

        states = np.asarray(
            self.states,
            dtype=np.float32,
        )

        actions = np.asarray(
            self.actions,
            dtype=np.float32,
        )

        rewards = np.asarray(
            self.rewards,
            dtype=np.float32,
        )

        if len(states) != len(actions) + 1:
            raise RuntimeError(
                "Invalid episode structure: expected "
                "len(states) == len(actions) + 1."
            )

        if len(actions) != len(rewards):
            raise RuntimeError(
                "Invalid episode structure: expected "
                "len(actions) == len(rewards)."
            )

        insert_nll = trajectory_nll(
            actor=actor,
            states=states[:-1],
            actions=actions,
        )

        episode = EpisodeRecord(
            episode_id=int(
                self.episode_id
            ),
            states=states,
            actions=actions,
            rewards=rewards,
            episode_return=self.episode_return,
            insert_step=int(
                insert_step
            ),
            insert_nll=float(
                insert_nll
            ),
            initial_env_state=self.initial_env_state,
            source="policy",
        )

        return episode


def finalize_and_add_to_vem(
    tracker: EpisodeTracker,
    actor,
    insert_step: int,
    vem: ValuableEpisodicMemory,
):
    """
    Finalize an episode and attempt admission into VEM.

    Returns:
        (episode, retained)

    episode:
        EpisodeRecord when the episode was fully policy-generated.
        None when it contained random/warm-up actions.

    retained:
        True if the episode is present in VEM after admission.
    """

    episode = tracker.finalize(
        actor=actor,
        insert_step=insert_step,
    )

    if episode is None:
        return None, False

    retained = vem.add(
        episode
    )

    return episode, retained
